### ISSUE TITLE
Plan for UI

### ISSUE THREAD

**Issue by geojaz** [cloudytimemachine/frontend#3]
Need to come to a consensus/sketch some wireframes that we can code to.

**Comment by rosskukulinski** [comment]
![f4c5f6fb-9de9-4e27-bc65-8662d1c08b62](https://cloud.githubusercontent.com/assets/2746479/18213855/3a94b5aa-7118-11e6-88bb-17d255b3a7ca.png)

@geojaz here's a starting point for you to do a first pass on wireframe.

**Comment by geojaz** [comment]
@rosskukulinski Here's a rough draft. These can be opened in draw.io.

[CTM Wireframes.zip](https://github.com/cloudytimemachine/frontend-static/files/453516/CTM.Wireframes.zip)

**Comment by rosskukulinski** [comment]
Great!  I have only minor comments -- feel free to include them as you see fit and start implementing.

My biggest comment was that I think we should look to combine the 'domain_search' and 'capture details' views.  Either the "time machine" carousel is above or below the capture details.  OR, we steal from the Apple time machine look-and-feel and put the time-machine scroll on the right side

![time-machine-local-backups](https://cloud.githubusercontent.com/assets/2746479/18227398/d32fab5c-71f0-11e6-955e-66bd9a52b234.jpg)

Home:
- Random previous capture carousel - not sure what you're thinking, but we could  do something like: 

<img width="600" alt="carousel" src="https://cloud.githubusercontent.com/assets/2746479/18227352/aef687f2-71ef-11e6-8195-9136606f708f.png">

Domain_search:
- Let's hold off on the 'browse other captures' feature.  I think it's a good one, but not essential for MVP.

Advanced capture - let's punt this down the road a bit

**Comment by geojaz** [comment]
Perfect. I'm on board with all of this. I'll start implementing the static version and we can hook the data in next.
