### ISSUE TITLE
Search box doesn't work

### ISSUE THREAD

**Issue by rosskukulinski** [cloudytimemachine/frontend#43]
Hi @geojaz - I think we're in pretty good shape for this week, but I did notice that the search box in the top right of the screen does not request updated data.

Could you take a look?

![ulgjkaxofu](https://cloud.githubusercontent.com/assets/2746479/19645839/d137504c-99c4-11e6-959d-53b0078a0508.gif)

**Comment by geojaz** [comment]
@rosskukulinski I'm on it!

**Comment by rosskukulinski** [comment]
🙏
