### ISSUE TITLE
Copywrite update

### ISSUE THREAD

**Issue by rosskukulinski** [cloudytimemachine/frontend#9]
Attribute to 'Ross Kukulinski, Eric Hole, and Contributors" and link it to github.com/cloudytimemachine

![screen shot 2016-09-08 at 8 10 41 am](https://cloud.githubusercontent.com/assets/2746479/18348859/da49d72e-759b-11e6-87d0-625287b4e4dd.png)

**Comment by geojaz** [comment]
Should this tag read (c) Ross Kukulinski, Eric Hole and Contributors?

**Comment by rosskukulinski** [comment]
Yep!  And `Contributors` can link to github.com/cloudytimemachine
